// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqbsfiqkjqvyurpwdqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxYnNmaXFranF2eXVycHdkcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzUzMjEsImV4cCI6MjA2NzA1MTMyMX0.sfPW0YdY3ZaqZCfobCT0upZttKp-CNG2yxlaGJD6m0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});